# Generated by Django 5.2.4 on 2025-08-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_friends_friendshiprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='friendshiprequest',
            unique_together={('created_by', 'created_for')},
        ),
    ]
